# Dockerfile.ojs
FROM pkpofficial/ojs:3_3_0-17

# # Instalar extensões PHP necessárias
RUN apk add --no-cache \
#     php81-bcmath \
#     php81-bz2 \
#     php81-calendar \
#     php81-ctype \
#     php81-curl \
#     php81-dom \
#     php81-exif \
#     php81-fileinfo \
#     php81-ftp \
    php81-gd \
#     php81-gettext \
#     php81-intl \
#     gnu-libiconv \
#     php81-json \
#     php81-mbstring \
    php81-pgsql \
    php81-pdo_pgsql \
#     php81-opcache \
#     php81-openssl \
#     php81-phar \
#     php81-session \
#     php81-simplexml \
#     php81-xml \
#     php81-xmlreader \
#     php81-xmlwriter \
    php81-zip \
    php81-zlib

# Criar diretórios para volumes
# RUN mkdir -p /var/www/files \
#     && mkdir -p /var/www/html/public \
#     && chown -R www-data:www-data /var/www

# COPY ./volumes/private /var/www/files
# COPY ./volumes/public /var/www/html/public
#      # WARNING: You can only enable file-volumes if file exists in the container.
RUN rm /var/www/html/config.inc.php
COPY ./volumes/config/config.inc.php /var/www/html/config.inc.php

# Não é necessário em produção
# COPY ./volumes/config/.htaccess /var/www/html/.htaccess

# correções de códigos
# RUN rm /var/www/html/plugins/generic/pdfJsViewer/pdf.js/web/viewer.js
# RUN rm /var/www/html/plugins/generic/pdfJsViewer/pdf.js/web/viewer.js.map
COPY ./volumes/correcoes/display.tpl /var/www/html/plugins/generic/pdfJsViewer/templates/display.tpl
COPY ./volumes/correcoes/viewer.js /var/www/html/plugins/generic/pdfJsViewer/pdf.js/web/viewer.js
COPY ./volumes/correcoes/viewer.js.map /var/www/html/plugins/generic/pdfJsViewer/pdf.js/web/viewer.js.map
COPY ./volumes/correcoes/PKPRequest.inc.php /var/www/html/lib/pkp/classes/core/PKPRequest.inc.php
# COPY ./volumes/config/update-ojs.sh /tmp/update.sh

# Torne o script executável
# RUN chmod +x /tmp/update.sh

# Defina ENTRYPOINT e CMD
# ENTRYPOINT ["/tmp/update.sh"]

# RUN sh /usr/local/bin/ojs-upgrade

# Portas expostas
EXPOSE 80
EXPOSE 443

# Comando de inicialização (use o mesmo da imagem original)
# CMD ["apache2-foreground"]
CMD ["ojs-start"]